### ISSUE TITLE
Generate DSMs and File co-edition graphs

### ISSUE THREAD

**Issue by jbon** [OPEN-NEXT/wp2.2_dev#17]
related to #18 

 - [x] test the script on more repositories
 - [x] feed the script a list of repositories instead of one at a time (new config parameter; issue #19)
 - [ ] Identity management (issue #15)
 - [x] Pull github issues (issue #20)
 - [ ] Generate interaction graphs based on file co-edition and issue participation (#23)
 - [ ] Generate DSMs based on file co-edition and issue participation
   - [ ] first: test with considering a link between files when they are showing up in the same commit.
   - [ ] second: experiment with weighting between files depending on the frequency of their co-editions within commits.

**Comment by jbon** [comment]
I take the item " Generate interaction graphs based on file co-edition and issue participation"
